/**
 * Fairy Permaculture — SoilField.
 *
 * Per-tile soil state for the whole 500×500 homestead, held in
 * typed arrays for cache-friendly per-day iteration. ~8 MB at full
 * scale, so this fits comfortably in memory.
 *
 * Values tracked per tile:
 *   om      — organic matter % (0–20)
 *   ph      — pH (3–10)
 *   nAvail  — plant-available nitrogen (kg/ha equivalent, scaled)
 *   pAvail  — plant-available phosphorus
 *   kAvail  — plant-available potassium
 *   moisture — % of field-capacity-adjusted water
 *   fb      — fungal:bacterial ratio (0.01 weed-stage → 10000 old-growth)
 *   biology — normalized biology index (0–1); proxy for microbial biomass
 *
 * The per-day `tick()` runs simplified nutrient-cycle math. The model
 * is intentionally sparse: headline dynamics only (mineralization,
 * moisture balance, OM decay). The goal is plausible game behavior,
 * not scientific accuracy.
 */

/**
 * Creates a SoilField. Optional `mapTiles` defaults to 500; useful
 * to pass a smaller number for tests.
 */
export function createSoilField(mapTiles = 500) {
  const n = mapTiles * mapTiles;
  const data = {
    mapTiles,
    om: new Float32Array(n),
    ph: new Float32Array(n),
    nAvail: new Float32Array(n),
    pAvail: new Float32Array(n),
    kAvail: new Float32Array(n),
    moisture: new Float32Array(n),
    fb: new Float32Array(n),
    biology: new Float32Array(n),
  };
  return data;
}

/**
 * Initialize from a procgen soil distribution (OM Float32Array)
 * generated by the biome module. Everything else gets sensible
 * defaults weighted by OM.
 */
export function initializeFromOmField(field, omField) {
  const n = field.om.length;
  if (omField.length !== n) {
    throw new Error(
      `omField length ${omField.length} does not match soil field size ${n}`
    );
  }
  for (let i = 0; i < n; i++) {
    const om = omField[i];
    field.om[i] = om;
    // Defaults scale with OM — real-world-ish starting points.
    field.ph[i] = 6.2;
    field.nAvail[i] = om * 3; // richer OM soils have more available N
    field.pAvail[i] = 8 + om * 0.5;
    field.kAvail[i] = 30 + om * 1.5;
    field.moisture[i] = 45 + Math.min(om, 5) * 1; // higher OM → a few % more moisture holding
    field.fb[i] = Math.max(0.5, om / 4); // more OM → more fungal
    field.biology[i] = Math.min(1, om / 6); // proxy
  }
  return field;
}

export function tileIndex(field, x, y) {
  return y * field.mapTiles + x;
}

export function getTile(field, x, y) {
  const i = tileIndex(field, x, y);
  return {
    om: field.om[i],
    ph: field.ph[i],
    nAvail: field.nAvail[i],
    pAvail: field.pAvail[i],
    kAvail: field.kAvail[i],
    moisture: field.moisture[i],
    fb: field.fb[i],
    biology: field.biology[i],
  };
}

/**
 * Apply compost to a tile. Quality 1-5 affects OM boost + biology.
 * See plan §Compost Economy.
 */
export function applyCompost(field, x, y, quality, m3 = 1.0) {
  const i = tileIndex(field, x, y);
  const q = Math.max(1, Math.min(5, quality));
  const boost = m3 * 0.01 * (q / 3); // balance.compost.om_boost_per_m3_q3 = 0.01
  field.om[i] = Math.min(20, field.om[i] + boost);
  field.nAvail[i] += 2 * q;
  field.pAvail[i] += 1 * q;
  field.kAvail[i] += 1.5 * q;
  field.biology[i] = Math.min(1, field.biology[i] + 0.05 * q);
  // Compost shifts F:B toward balanced; hot compost more bacterial,
  // worm-cast / fungal-dominant compost more fungal — simplified here.
  field.fb[i] += (1 - field.fb[i]) * 0.05 * q;
}

/**
 * Run one day of soil dynamics across the whole field.
 *
 * env = { rainMm, tempC, evapBase, season }
 *
 * We keep the math simple and conservative-of-mass in the obvious
 * places (water in = water stored + evap + runoff). OM decays very
 * slowly without mineralization; N mineralizes from OM at a rate
 * proportional to biology + warmth.
 */
export function tickSoil(field, env) {
  const { rainMm = 0, tempC = 15, evapBase = 2.5 } = env;
  const n = field.om.length;

  // Temperature factor: microbial activity peaks around 25 °C.
  const tempFactor = Math.max(0, 1 - Math.abs(tempC - 25) / 25);

  for (let i = 0; i < n; i++) {
    // ── Moisture balance ─────────────────────────────────
    // Rain adds; evaporation removes; higher OM buffers.
    const evap = evapBase * Math.max(0.3, 1 - field.om[i] / 15);
    field.moisture[i] = clamp(field.moisture[i] + rainMm - evap, 0, 100);

    // ── Nitrogen mineralization from OM ──────────────────
    // Very small daily release proportional to biology * temp * OM.
    const mineralized = 0.02 * field.biology[i] * tempFactor * field.om[i];
    field.nAvail[i] += mineralized;

    // OM decays by a small fraction of what it mineralized (most of
    // its carbon stays parked). This keeps the books roughly sane.
    field.om[i] = Math.max(0.1, field.om[i] - mineralized * 0.02);

    // ── Leaching during heavy rain ───────────────────────
    // Cap at 40 %/day — soils don't flush 100 % of mineral N in one
    // downpour (plants + cation exchange + subsoil hold some).
    if (rainMm > 10) {
      const leach = Math.min(0.4, (rainMm - 10) / 50);
      field.nAvail[i] = Math.max(0, field.nAvail[i] - field.nAvail[i] * leach);
    }

    // ── Biology drift ────────────────────────────────────
    // If OM is high and moisture is good, biology trends up.
    const biologyTarget =
      Math.min(1, field.om[i] / 6) * Math.max(0.3, field.moisture[i] / 60);
    field.biology[i] += (biologyTarget - field.biology[i]) * 0.01;
  }
}

function clamp(v, lo, hi) {
  return v < lo ? lo : v > hi ? hi : v;
}

/**
 * Sum-of-organic-matter across all tiles, in arbitrary units. Useful
 * as a whole-farm "biomass in soil" metric for progress tracking and
 * the progression-simulator.
 */
export function totalOm(field) {
  let s = 0;
  for (let i = 0; i < field.om.length; i++) s += field.om[i];
  return s;
}

/** Conservation-of-mass sanity check for tests. */
export function totalNutrients(field) {
  let n = 0,
    p = 0,
    k = 0;
  for (let i = 0; i < field.om.length; i++) {
    n += field.nAvail[i];
    p += field.pAvail[i];
    k += field.kAvail[i];
  }
  return { n, p, k };
}

// ─── Save / Load ──────────────────────────────────────────────────
// The 500×500 typed arrays would balloon the save payload if we dumped
// each of the 8 channels in full. Full-fidelity persistence lives
// behind `serializeSoilFull` for deterministic round-trips in tests;
// the game save uses a lightweight summary via `serializeSoilSummary`.

/** Full-fidelity serialize: typed arrays → plain number arrays. */
export function serializeSoilFull(field) {
  return {
    version: 1,
    mode: "full",
    mapTiles: field.mapTiles,
    om: Array.from(field.om),
    ph: Array.from(field.ph),
    nAvail: Array.from(field.nAvail),
    pAvail: Array.from(field.pAvail),
    kAvail: Array.from(field.kAvail),
    moisture: Array.from(field.moisture),
    fb: Array.from(field.fb),
    biology: Array.from(field.biology),
  };
}

/**
 * Summary serialize — averages per-channel across the field. Combined
 * with the biome seed (heightfield + OM distribution regenerate
 * deterministically from the seed), this is enough to restore the
 * soil state to within a few percent of its saved value.
 *
 * Restore re-initializes the field from the biome seed + overlays the
 * summary deltas. MVP save uses this mode by default.
 */
export function serializeSoilSummary(field) {
  const n = field.om.length;
  const acc = { om: 0, ph: 0, nAvail: 0, pAvail: 0, kAvail: 0, moisture: 0, fb: 0, biology: 0 };
  for (let i = 0; i < n; i++) {
    acc.om += field.om[i];
    acc.ph += field.ph[i];
    acc.nAvail += field.nAvail[i];
    acc.pAvail += field.pAvail[i];
    acc.kAvail += field.kAvail[i];
    acc.moisture += field.moisture[i];
    acc.fb += field.fb[i];
    acc.biology += field.biology[i];
  }
  return {
    version: 1,
    mode: "summary",
    mapTiles: field.mapTiles,
    averages: {
      om: acc.om / n,
      ph: acc.ph / n,
      nAvail: acc.nAvail / n,
      pAvail: acc.pAvail / n,
      kAvail: acc.kAvail / n,
      moisture: acc.moisture / n,
      fb: acc.fb / n,
      biology: acc.biology / n,
    },
  };
}

/** Hydrate a soil field from either full or summary payload. */
export function hydrateSoil(field, saved) {
  if (!saved) return field;
  if (saved.mapTiles && saved.mapTiles !== field.mapTiles) {
    throw new Error(
      `hydrateSoil: mapTiles mismatch (saved=${saved.mapTiles}, field=${field.mapTiles})`
    );
  }
  const n = field.om.length;
  if (saved.mode === "full") {
    field.om.set(saved.om);
    field.ph.set(saved.ph);
    field.nAvail.set(saved.nAvail);
    field.pAvail.set(saved.pAvail);
    field.kAvail.set(saved.kAvail);
    field.moisture.set(saved.moisture);
    field.fb.set(saved.fb);
    field.biology.set(saved.biology);
    return field;
  }
  if (saved.mode === "summary") {
    const a = saved.averages ?? {};
    for (let i = 0; i < n; i++) {
      if (a.om != null) field.om[i] = a.om;
      if (a.ph != null) field.ph[i] = a.ph;
      if (a.nAvail != null) field.nAvail[i] = a.nAvail;
      if (a.pAvail != null) field.pAvail[i] = a.pAvail;
      if (a.kAvail != null) field.kAvail[i] = a.kAvail;
      if (a.moisture != null) field.moisture[i] = a.moisture;
      if (a.fb != null) field.fb[i] = a.fb;
      if (a.biology != null) field.biology[i] = a.biology;
    }
    return field;
  }
  throw new Error(`hydrateSoil: unknown mode '${saved.mode}'`);
}
